AllCops:
  Exclude:
    - 'app/main.rb'
    - Gemfile
    - Gemfile.lock
  NewCops: enable

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Style/GlobalVars:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false