name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run rubocop with reviewdog
      uses: reviewdog/action-rubocop@v1
