# .github/workflows/rubocop.yml

name: YARD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.0.2 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.2 # Replace with your ruby version
    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: YARD
      -run: yard doc -m markdown -o docs --exclude app/main.rb 
